### PR TITLE
Change Inverse to Alinto in README

### PR DESCRIPTION
**Pull request by modir**
I am not sure how exactly Alinto sees the license situation regarding Active Sync. Maybe your lawyer want to change even more than just this word.

### CODE REVIEW

**Comment by modir** [comment]
In the same directory is a file LICENSE where probably Inverse needs to be changed to Alinto as well.

**Comment by WoodySlum** [comment]
Inverse is still the owner of what they produced

**Comment by WoodySlum** [comment]
It should be `Inverse Inc and Alinto`

**Comment by Neustradamus** [comment]
@WoodySlum: Why it is closed?

**Comment by WoodySlum** [comment]
The PR has not changed according to comments. This task will be processed in https://bugs.sogo.nu/view.php?id=6026

**Pull request closed without merging**
