### PR TITLE
Adjust imap authenticate documentation

### PR DESCRIPTION
**Pull request by ichdasich**
This pull-request updates the default configuration file and the documentation to highlight that `NGImap4AuthMechanism = "plain";` should be set to force `AUTHENTICATE` usage if users' passwords may contain UTF-8 characters like umlauts.

Otherwise, users may update their passwords via SOGo to ones containing an UTF-8 character, which then inadvertedly breaks the mail view, as logging in via `LOGIN` is no longer possible. Logging into SOGo itself still works, but users are presented with a white page when trying to access the mail view.

***Security Side Note:*** Depending on the setup it seems to be possible to lock up SOGo worker threads using this, ultimately leading to a DoS (as soon as all workers are busy for this user). Specifically, I just had one user on a small (20 worker threads) instance setting a password containing an umlaut. As the user tried to log in multiple times, ultimately all workers were busy with trying to authenticate to the IMAP server. I did not fully debug this, but there might also be some malicious potential in this for some malicious activity.

### CODE REVIEW

**Comment by ichdasich** [comment]
Thanks, will take a look; Sorry, this was created in the middle of the night after a rather painfull debugging session, so i do not forget. ;-)

**Comment by WoodySlum** [comment]
No problem thanks for your support !

**Comment by ichdasich** [comment]
Changed the messages, does this work?

**Comment by WoodySlum** [comment]
Nice ! Thank you !

**Pull request merged**
