### PR TITLE
fix(eas) use bare email address (fixes #5612)

### PR DESCRIPTION
**Pull request by tfux**
Use just the bare email address for sendMail.

### CODE REVIEW

**Comment by WoodySlum** [comment]
Hi @tfux thank you for the fix.
Would it be possible to set `3` in constant ? This will make the value of 3 more understandable.

**Comment by tfux** [comment]
Can you please give an example.
You could also take the fix as is and improve as needed.

**Comment by WoodySlum** [comment]
I suggest replacing 

```
for (count = 0; count < 3; count++)
```

with

```
for (count = 0; count < (sizeof(fieldNames) / sizeof(NSString)); count++)
```

Are you ok with this change ?

And also : 

```
allRecipients = [NSMutableArray arrayWithCapacity: 16];
```

Could you explained why 16 ?

**Comment by tfux** [comment]
Code is actually just a copy from SOGoDraftObject.m.

**Comment by WoodySlum** [comment]
I tried to refactor the code. Could you please test that the fix is still efficient on branch `fix-5612` ?

**Comment by tfux** [comment]
I get the following when trying to compile branch fix-5612.

In file included from NGMimeMessage+ActiveSync.m:30:
NGMimeMessage+ActiveSync.h:34:9: fatal error: SOGoMailBaseObject.h: No such file or directory
   34 | #import "SOGoMailBaseObject.h"
      |         ^~~~~~~~~~~~~~~~~~~~~~

...
...
In file included from NGMimeMessage+ActiveSync.m:30:
NGMimeMessage+ActiveSync.h:39:39: error: expected identifier or ‘(’ before ‘:’ token
   39 | @interface NGMimeMessage (ActiveSync) : SOGoMailBaseObject
      |

**Comment by WoodySlum** [comment]
As I don't have enough time at this moment, I suggest to merge as it is and do the rework to avoid duplicate code later.

**Pull request merged**
